"""End-to-end RAG robustness pipeline - CLI entry point.

Two dataset paths are supported and selected via ``--dataset``:

- ``fever``     → load_fever / FeverTask (claim verification)
- ``hotpotqa``  → load_hotpotqa / HotpotQATask (multi-hop QA)

Poisoned examples are loaded from pre-computed JSONL files generated by
``scripts/precompute_negations.py``.  The pipeline itself never calls an LLM
for negation, ensuring all evaluated models face the same attack data.
"""
import argparse
import json
import os
from dataclasses import dataclass, field
from typing import Callable, Optional

import yaml

from src.data.fever_loader import load_fever
from src.data.hotpotqa_loader import load_hotpotqa
from src.evaluation.pipeline import run_pipeline
from src.evaluation.qa_scorer import HotpotQATask
from src.evaluation.scorer import FeverTask
from src.generation.llm_client import HuggingFaceClient
from src.retrieval.embedder import Embedder
from src.retrieval.retriever import Retriever


@dataclass(frozen=True)
class DatasetRunner:
    """Single registration point for one dataset.

    loader:          (cfg, n) -> list[dict]  — loads clean examples
    task:            EvaluationTask adapter
    default_prompt_fn: resolves the default prompt-type string from the config dict.
    poisoned_loader: (cfg, n) -> list[dict]  — loads pre-computed poisoned examples,
                     or None if no pre-computed file is configured.
    """
    loader: Callable[..., list[dict]]
    task: object
    default_prompt_fn: Callable[[dict], str]
    poisoned_loader: Optional[Callable] = field(default=None)


def load_config(path: str) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def _build_llm(model: str, cfg: dict):
    cache_dir = os.path.join(cfg["cache"]["dir"], cfg["cache"]["llm_subdir"])
    temperature = cfg["models"]["temperature"]
    return HuggingFaceClient(model=model, temperature=temperature, cache_dir=cache_dir)


_DATASET_REGISTRY: dict[str, DatasetRunner] = {
    "fever": DatasetRunner(
        loader=lambda cfg, n: load_fever(cfg["dataset"]["fever_dev"], max_examples=n),
        task=FeverTask(),
        default_prompt_fn=lambda cfg: cfg["prompts"]["default"],
        poisoned_loader=lambda cfg, n: load_fever(
            cfg["dataset"]["fever_dev_poisoned"], max_examples=n
        ),
    ),
    "hotpotqa": DatasetRunner(
        loader=lambda cfg, n: load_hotpotqa(cfg["dataset"]["hotpotqa_dev"], max_examples=n),
        task=HotpotQATask(),
        default_prompt_fn=lambda cfg: cfg["prompts"].get("default_qa", "standard_qa"),
        poisoned_loader=lambda cfg, n: load_hotpotqa(
            cfg["dataset"]["hotpotqa_dev_poisoned"], max_examples=n
        ),
    ),
}


def main(argv=None) -> dict:
    parser = argparse.ArgumentParser(description="RAG robustness pipeline")
    parser.add_argument("--config", default="configs/config.yaml", help="Path to config.yaml")
    parser.add_argument("--dataset", default=None, choices=list(_DATASET_REGISTRY))
    parser.add_argument("--n", type=int, default=None, help="Number of examples (overrides config)")
    parser.add_argument("--poison_rate", type=float, default=None,
                        help="0.0 (clean) or 1.0 (fully poisoned)")
    parser.add_argument("--model", default=None, help="LLM model name")
    parser.add_argument(
        "--prompt_type",
        default=None,
        choices=["standard", "chain_of_thought", "vigilant", "standard_qa", "cot_qa", "vigilant_qa"],
    )
    parser.add_argument("--seed", type=int, default=None)
    args = parser.parse_args(argv)

    cfg = load_config(args.config)

    seed = args.seed if args.seed is not None else cfg["seed"]
    n = args.n if args.n is not None else cfg["evaluation"]["n_examples"]
    poison_rate = args.poison_rate if args.poison_rate is not None else cfg["poisoning"]["poison_rate"]
    model = args.model if args.model is not None else cfg["models"]["default"]
    dataset = args.dataset if args.dataset is not None else cfg["dataset"].get("default", "fever")

    emb_cache = os.path.join(cfg["cache"]["dir"], cfg["cache"]["embeddings_subdir"])
    embedder = Embedder(
        model_name=cfg["retrieval"]["embedding_model"],
        cache_dir=emb_cache,
    )
    retriever = Retriever(embedder=embedder, k=cfg["retrieval"]["k"])
    llm = _build_llm(model, cfg)

    with embedder, llm:
        ds = _DATASET_REGISTRY[dataset]
        prompt_type = args.prompt_type if args.prompt_type is not None else ds.default_prompt_fn(cfg)

        if poison_rate > 0.0:
            if ds.poisoned_loader is None:
                raise ValueError(
                    f"Dataset '{dataset}' has no pre-computed poisoned data. "
                    f"Run: python scripts/precompute_negations.py --dataset {dataset}"
                )
            examples = ds.poisoned_loader(cfg, n)
        else:
            examples = ds.loader(cfg, n)

        metrics = run_pipeline(
            ds.task,
            examples,
            retriever,
            llm,
            prompt_type=prompt_type,
            seed=seed,
        )

    run_cfg = {
        "dataset": dataset,
        "n": n,
        "poison_rate": poison_rate,
        "model": model,
        "prompt_type": prompt_type,
        "seed": seed,
    }
    print(json.dumps({"config": run_cfg, "metrics": metrics}, indent=2))
    return metrics


if __name__ == "__main__":
    main()
